CREATE TABLE Records
(
    id             int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    artist         varchar(100) NOT NULL,
    album          varchar(100) NOT NULL,
    datarecording  varchar(100) NOT NULL,
    datareliase    varchar(100) NOT NULL,
    publhouse      varchar(100) NOT NULL,
    country        varchar(100) NOT NULL,
    genry          varchar(100) NOT NULL,
    numberoftracks varchar(100) NOT NULL,
    numberofdisk   varchar(100) NOT NULL,
    conditions     varchar(100) NOT NULL

);

INSERT INTO Records (artist, album, datarecording, datareliase, publhouse, country, genry, numberoftracks, numberofdisk,
                     conditions)
VALUES ('The Rolling Stones', 'Sticky Fingers', '1971-03-23', '1971-04-23', 'Rolling Stones Records', 'United Kingdom',
        'Rock', '10', '1', 'Excellent'),
       ('Led Zeppelin', 'IV', '1971-12-08', '1971-11-08', 'Atlantic Records', 'United States', 'Rock', '8', '1',
        'Very Good'),
       ('The Beatles', 'Abbey Road', '1969-02-22', '1969-09-26', 'Apple Records', 'United Kingdom', 'Rock', '17', '1',
        'Good'),
       ('Pink Floyd', 'The Dark Side of the Moon', '1972-05-23', '1973-03-24', 'Harvest Records', 'United Kingdom',
        'Progressive Rock', '10', '1', 'Excellent'),
       ('The Who', 'Whos Next', '1971-05-15', '1971-08-14', 'Decca Records', 'United Kingdom', 'Rock', '9', '1',
        'Very Good'),
       ('Queen', 'A Night at the Opera', '1975-08-10', '1975-11-21', 'EMI Records', 'United Kingdom', 'Rock', '12', '1',
        'Excellent'),
       ('The Doors', 'L.A. Woman', '1970-12-05', '1971-04-19', 'Elektra Records', 'United States', 'Rock', '10', '1',
        'Good'),
       ('Deep Purple', 'Machine Head', '1971-12-06', '1972-03-25', 'Purple Records', 'United Kingdom', 'Hard Rock', '7',
        '1', 'Very Good'),
       ('Jimi Hendrix', 'Are You Experienced', '1966-12-05', '1967-05-12', 'Track Records', 'United Kingdom', 'Rock',
        '11', '1', 'Good'),
       ('AC/DC', 'Back in Black', '1980-07-25', '1980-07-25', 'Atlantic Records', 'United States', 'Hard Rock', '10',
        '1', 'Excellent');

DROP table Records;



CREATE TABLE Users
(
    id              int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            varchar(100) NOT NULL,
    last_name       varchar(100) NOT NULL,
    email           varchar(100) NOT NULL,
    phone           varchar(100) NOT NULL,
    country         varchar(100) NOT NULL,
    city_or_village varchar(100) NOT NULL,
    login           varchar(100) NOT NULL,
    password        varchar(100) NOT NULL
);



INSERT INTO Users (name, last_name, email, phone, country, city_or_village, login, password)
VALUES ('John', 'Doe', 'john.doe@example.com', '1234567890', 'USA', 'New York', 'john_doe', 'pass123'),
       ('Alice', 'Smith', 'alice.smith@example.com', '0987654321', 'Canada', 'Toronto', 'alice_smith', 'pass456'),
       ('Bob', 'Johnson', 'bob.johnson@example.com', '5678901234', 'UK', 'London', 'bob_johnson', 'pass789');


DROP table Users;
